services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: mip-backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: mip-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend