services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: assetwize-backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
      args:
        VITE_API_BASE_URL: http://127.0.0.1:8000
    container_name: assetwize-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend